---
  section:
    programs:
      title: "Do you want to learn how to program?"
      undertitle: "Get access to tutorials. Talk and learn from leading IT-specialists."
    teacher:
      title: "Teacher of the highest category"
      undertitle: "All our teachers have a wealth of knowledge and experience on the shoulders"
    course:
      title: "Our best courses"
      undertitle: "We give you the knowledge of the most modern and advanced technologies in the development of the world"
    registration:
      title: "Are you ready to start training?"
      undertitle: "You only need to fill out the form below and click on the forward button"